framework:
    rate_limiter:
        lost_credentials:
            policy: 'fixed_window'
            limit: 20
            interval: '60 minutes'
        test_mails:
            policy: 'fixed_window'
            limit: 5
            interval: '30 minutes'
